endroid_qr_code:
    user_details_svg:
        writer: Endroid\QrCode\Writer\SvgWriter
        error_correction_level: 'medium' # 'low', 'medium', 'quartile', or 'high'
        round_block_size_mode: 'none'
        writer_options:
            exclude_svg_width_and_height: true
    card_png:
        writer: Endroid\QrCode\Writer\PngWriter
        error_correction_level: 'medium'
        size: 300
