hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        keycloak:
            type: keycloak
            base_url: https://accounts.fablab-altmuehlfranken.de
            realm: fablab
            client_id: ausweis
            client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'
            options:
                idp_hint: FabLab Account
            paths:
                identifier: preferred_username
